name: GeneDocs

on:
  push:
    tags:
      - publish.**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: gradleWrapper
      - name: Generate Docs
        run: |
          chmod +x gradlew
          ./gradlew geneDocs -PmavenUsername=${{ secrets.M2_USERNAME }} -PmavenPassword=${{ secrets.M2_PASSWORD }}
          ./gradlew clean -PmavenUsername=${{ secrets.M2_USERNAME }} -PmavenPassword=${{ secrets.M2_PASSWORD }}
      - name: Create Commit
        run: |
          git add ./docs
          git commit -m "update Docs by github actions"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
