name: Java CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: gradleWrapper
      - name: Generate Docs
        run: |
          chmod +x gradlew
          ./gradlew geneDocs
      - name: Push Docs
        uses: EndBug/add-and-commit@v7
        with:
          add: 'docs'
          message: 'update docs by github action'
